AngryEggplantStudios/CULLinary2

CULLinary2/Assets/Prefabs/Ported Over/Prefabs/DungeonRooms/Combined/Room 0.prefab
CULLinary2/Assets/Prefabs/Ported Over/Prefabs/DungeonRooms/Material/UniversalRenderPipelineAsset.asset
CULLinary2/Assets/Scenes/Dungeon.unity
CULLinary2/ProjectSettings/TagManager.asset
CULLinary2/UserSettings/EditorUserSettings.asset

Forgot to change the materials on one of the prefabs

Fix materials

---

CULLinary2/Assets/Scenes/DemoScene.unity
CULLinary2/Assets/Scripts/Dungeon/Orders/OrderSlot.cs
CULLinary2/Assets/Scripts/Dungeon/Orders/OrdersManager.cs
CULLinary2/Assets/Scripts/Dungeon/Orders/PlayerOrders.cs
CULLinary2/Assets/Scripts/Dungeon/Recipes/RecipeManager.cs

Some changes so the orders in the list are generated every day, based on GameTimer

Generate random orders on new day

---

CULLinary2/Assets/Prefabs/UI/UI_New.prefab
CULLinary2/Assets/Scripts/Dungeon/Minimap.cs
CULLinary2/Assets/Scripts/Dungeon/Recipes/CookingStation.cs
CULLinary2/Assets/Scripts/Dungeon/Recipes/RecipeManager.cs

Similar implementation to Orders icons. Probably there is a more efficient way to do it rather than looping through 20+ icons each Update, but this will do for now

Add campfire icons to minimap

---

CULLinary2/Assets/Prefabs/UI/UI_New.prefab
CULLinary2/Assets/Scripts/Dungeon/Minimap.cs

Now, the icons will no longer gather in a circle

Let icons go to edge of rectangular minimap

---

CULLinary2/Assets/Art/UI/Mockups/Die.png.meta
CULLinary2/Assets/Prefabs/UI/Panels/PlayerDeathPanel.prefab
CULLinary2/Assets/Prefabs/UI/UI_New.prefab
CULLinary2/Assets/Scenes/MainScene.unity

Add death menu

---

CULLinary2/Assets/Art/UI/Mockups/Win (1).png.meta
CULLinary2/Assets/Experiment/TestScripts/Dungeon Scripts/Boss/ClownController.cs
CULLinary2/Assets/Prefabs/Archive/Prefabs/DungeonEnemies/EnemyAlert.prefab
CULLinary2/Assets/Prefabs/Enemies/BossWithSpawns.prefab
CULLinary2/Assets/Prefabs/Player/Chef_New_Playable.prefab
CULLinary2/Assets/Prefabs/UI/Panels/WinPanel.prefab
CULLinary2/Assets/Prefabs/UI/Panels/WinPanel.prefab.meta
CULLinary2/Assets/Prefabs/UI/UI_New.prefab
CULLinary2/Assets/Prefabs/UI/WinStatistics.prefab
CULLinary2/Assets/Prefabs/UI/WinStatistics.prefab.meta
CULLinary2/Assets/Scenes/MainScene.unity
CULLinary2/Assets/Scripts/Special Events/SpecialEventManager.cs
CULLinary2/Assets/Scripts/UI/UIController.cs

* Show win screen after defeating boss

Add win screen

---

CULLinary2/Assets/Prefabs/UI/Tabs/CreaturesUI.prefab
CULLinary2/Assets/Prefabs/UI/Tabs/InventoryUI.prefab
CULLinary2/Assets/Prefabs/UI/Tabs/MapUI.prefab
CULLinary2/Assets/Prefabs/UI/Tabs/OrdersUI.prefab
CULLinary2/Assets/Prefabs/UI/Tabs/RecipesUI.prefab
CULLinary2/Assets/Prefabs/UI/UI_New.prefab
CULLinary2/Assets/Scripts/UI/UIController.cs

* Also, remove Creatures tab (at least, it is hidden for now)

Add new tabs to all interfaces

---

CULLinary2/Assets/Models/Corn/CornMiniBoss.prefab
CULLinary2/Assets/Models/Eggplant/EggplantMiniBoss.prefab
CULLinary2/Assets/Models/Potato/PotatoMiniBoss.prefab
CULLinary2/Assets/Scenes/MainScene.unity
CULLinary2/Assets/Scripts/Dungeon/Enemies/MiniBoss.cs
CULLinary2/Assets/Scripts/Dungeon/Enemies/MonsterScript.cs
CULLinary2/Assets/Scripts/Dungeon/GameTimer.cs
CULLinary2/Assets/Scripts/Ecosystem/EcosystemManager.cs

* And assign stop chase stat for miniboss

Fix bug for assigning miniboss health

---

CULLinary2/Assets/Prefabs/Archive/Prefabs/DungeonEnemies/EnemyAlert.prefab
CULLinary2/Assets/Prefabs/Enemies/BossWithSpawns.prefab
CULLinary2/Assets/Scripts/Dungeon/Enemies/MonsterBehavior.cs
CULLinary2/Assets/Scripts/Dungeon/Enemies/MonsterScript.cs
CULLinary2/Assets/Scripts/Dungeon/Misc (Animator)/Dungeon/Enemies/CornNewController.controller
CULLinary2/Assets/Scripts/Dungeon/Misc (Animator)/Dungeon/Enemies/PotatoControllerNew.controller
CULLinary2/Assets/Scripts/Dungeon/Misc (Animator)/Dungeon/Enemies/eggplantNewAnimator.controller

- Fix enemies not disappearing after being killed.

Fix ghost enemies

---

CULLinary2/Assets/Prefabs/Archive/Prefabs/DungeonEnemies/ItemPickupNotif.prefab
CULLinary2/Assets/Prefabs/UI/Campfire/CookingUI.prefab
CULLinary2/Assets/Prefabs/UI/Campfire/ShopUI.prefab
CULLinary2/Assets/Prefabs/UI/Campfire/WeaponUI.prefab
CULLinary2/Assets/Scenes/MainScene.unity
CULLinary2/Assets/Scripts/Dungeon/Inventory/ItemPickupNotif.cs
CULLinary2/Assets/Scripts/Dungeon/Recipes/CookingStation.cs
CULLinary2/Assets/Scripts/Dungeon/Recipes/RecipeManager.cs
CULLinary2/Assets/Scripts/Dungeon/Shop/ShopManager.cs
CULLinary2/Assets/Scripts/System/PlayerKeybinds.cs
CULLinary2/Assets/Scripts/UI/UIController.cs

* Menu/Tabs and campfire now cannot be opened on top of each other
* Use interact key F to toggle campfire menu
* Use campfire action key Z to buy or cook instead
* Add item pickup notification for cooking, based on latest cooking UI design

Several UI tweaks and fixes

---

CULLinary2/Assets/Models/Corn/CornEnemyNew.prefab
CULLinary2/Assets/Scripts/Dungeon/Enemies/MonsterScript.cs
CULLinary2/Assets/Scripts/Dungeon/Enemies/MonsterVaryColour.cs
CULLinary2/Assets/Scripts/Dungeon/Enemies/MonsterVaryColour.cs.meta

Also, fix monster flash when taking damage

Add coloured corn

---

CULLinary2/Assets/Prefabs/Loot/PotionLoot.prefab
CULLinary2/Assets/Prefabs/Loot/PotionLoot.prefab.meta
CULLinary2/Assets/Prefabs/Player/Chef_New_Playable.prefab
CULLinary2/Assets/Scenes/MainScene.unity
CULLinary2/Assets/Scripts/Dungeon/Inventory/PotionLoot.cs
CULLinary2/Assets/Scripts/Dungeon/Inventory/PotionLoot.cs.meta
CULLinary2/Assets/Scripts/Player/PlayerPickup.cs

Oops, forgot to push my latest changes :S

Actually add potion loot

---

CULLinary2/Assets/Prefabs/UI/RecipeBase.prefab
CULLinary2/Assets/Prefabs/UI/Tabs/InventoryUI.prefab
CULLinary2/Assets/Prefabs/UI/UI_New.prefab
CULLinary2/Assets/Prefabs/UI/UI_New_Copy.prefab
CULLinary2/Assets/Scenes/MainScene.unity
CULLinary2/Assets/Scripts/Dungeon/Enemies/MonsterBaseSpawning.cs

...with player and objects spawned in map

Check for collision when spawning base monsters

---

CULLinary2/Assets/Models/Bread/BreadDed.anim
CULLinary2/Assets/Models/Corn/CornDeath.anim
CULLinary2/Assets/Models/Eggplant/EggplantNewDeath.anim
CULLinary2/Assets/Models/Potato/TomatoEnemy.prefab
CULLinary2/Assets/Models/Potato/potatoFlippedDeath.anim
CULLinary2/Assets/Models/Tomato/TomatoDeath.anim
CULLinary2/Assets/Scenes/MainScene.unity
CULLinary2/Assets/Scripts/Dungeon/Enemies/MonsterBehavior.cs
CULLinary2/Assets/Scripts/Dungeon/Enemies/MonsterScript.cs

- Fixes enemy stationary on the ground and not roaming properly
- Fix HpBar following player when dash away after enemy kill

Mc/Fix Enemy ai

---

CULLinary2/Assets/Scenes/MainScene.unity

A tiny change to make the newspaper look better

Justify newspaper titles

---

CULLinary2/Assets/Models/Bread/BreadEnemy.prefab
CULLinary2/Assets/Models/Tomato/Tomato.prefab
CULLinary2/Assets/Scenes/MainScene.unity
CULLinary2/Assets/Scripts/Dungeon/Minimap.cs
CULLinary2/Assets/Scripts/System/GameLoader.cs
CULLinary2/Assets/Scripts/Truck/DrivingManager.cs

* Add random colour for tomato and bread enemies
* Disable truck trails when summoning
* Remove truck from MainScene and UI maps when loaded

Add colour to tomato and bread, truck tweaks

---

CULLinary2/Assets/Scripts/Dungeon/Minimap.cs
CULLinary2/Assets/Scripts/Dungeon/PlayerInteractable.cs
CULLinary2/Assets/Scripts/Truck/DrivingManager.cs

* Fix missing minimap icons
* Fix null reference when summoning truck

Fix minimap icons disappearing

---

CULLinary2/Assets/Experiment/Prefabs/Boss/bossBurger.prefab
CULLinary2/Assets/Models/Mushroom/MushroomEnemy.prefab
CULLinary2/Assets/Prefabs/Archive/Prefabs/DungeonEnemies/EnemyAlert.prefab
CULLinary2/Assets/Prefabs/Enemies/BossWithSpawns.prefab
CULLinary2/Assets/Scenes/MainScene.unity
CULLinary2/Assets/Scripts/Dungeon/Enemies/CullableMushroom.cs
CULLinary2/Assets/Scripts/Dungeon/Enemies/CullableMushroom.cs.meta
CULLinary2/Assets/Scripts/Dungeon/Enemies/MonsterScript.cs
CULLinary2/Assets/Scripts/Util/ObjectCuller.cs

This PR fixes the spike caused in CPU by costly calls.

Fix mistake with mushroom

---

CULLinary2/Assets/Models/Corn/CornMiniBoss.prefab
CULLinary2/Assets/Models/Eggplant/EggplantMiniBoss.prefab
CULLinary2/Assets/Models/Potato/PotatoMiniBoss.prefab
CULLinary2/Assets/Scenes/MainScene.unity
CULLinary2/Assets/Scripts/Dungeon/Enemies/MiniBoss.cs

- Adjusts mini boss values slightly.

Slightly tweak mini boss values

---

CULLinary2/Assets/Scenes/MainScene.unity
CULLinary2/Assets/Scripts/Scriptable Objects/Others/UnlockTruckEvent.cs
CULLinary2/Assets/Scripts/System/PlayerKeybinds.cs
CULLinary2/Assets/Scripts/Truck/DrivingManager.cs
CULLinary2/Assets/Scripts/UI/SetUIControllerActiveTab.cs

Load from PlayerManager in DrivingManager

Add truck summon icon in UI

---

CULLinary2/Assets/Scenes/MainMenu.unity
CULLinary2/Assets/Scenes/TutorialScene.unity
CULLinary2/Assets/Scripts/Dungeon/Minimap.cs
CULLinary2/Assets/Scripts/Loading Scene/LoadScene.cs
CULLinary2/Assets/Scripts/Player/DatabaseLoader.cs
CULLinary2/Assets/Scripts/System/MenuController.cs
CULLinary2/Assets/Scripts/Tutorial/TutorialManager.cs
CULLinary2/Assets/Scripts/Tutorial/TutorialOrdersManager.cs
CULLinary2/Assets/Scripts/Tutorial/TutorialRecipeManager.cs
CULLinary2/Assets/Scripts/UI/OrdersUIMap.cs

* Main Menu now shows Tutorial instead of New Game when you do not have a saved file
* Tutorial will create saved files and biome files at the end and load MainScene
* Added Skip Tutorial button
* Fix some bugs with recipes, orders UI, and minimap in tutorial

Link up Tutorial to MainMenu and MainScene

---

CULLinary2/Assets/Scenes/LoadingScene.unity

Update loading screen scene

---

CULLinary2/Assets/Scenes/MainScene.unity
CULLinary2/Assets/Scenes/TutorialScene.unity
CULLinary2/Assets/Scripts/Player/PlayerManager.cs
CULLinary2/Assets/Scripts/System/Data/PlayerData.cs
CULLinary2/Assets/Scripts/Truck/CarController.cs
CULLinary2/Assets/Scripts/Truck/DrivingManager.cs
CULLinary2/Assets/Scripts/Truck/TruckTutorialManager.cs
CULLinary2/Assets/Scripts/Truck/TruckTutorialManager.cs.meta
CULLinary2/Assets/Scripts/Tutorial/TutorialManager.cs

* Truck tutorial status is saved in player data as a boolean
* No option to skip truck tutorial (anyway many do not know how to drive)
* Add "ding" sound to main tutorial also
* Fix main tutorial having cooking sound on startup

Add truck tutorial

---

CULLinary2/Assets/Prefabs/UI/OrdersUISlot.prefab
CULLinary2/Assets/Scenes/MainScene.unity
CULLinary2/Assets/Scenes/TutorialScene.unity
CULLinary2/Assets/Scripts/Dialogue/DialogueManager.cs
CULLinary2/Assets/Scripts/Tutorial/TutorialLoader.cs

* Fix skip dialogue text not hiding after skip
* Hide triangle for last dialogue in sequence
* Fix missing potatoes in TutorialScene
* Disable click for orders in UI

Dialogue fixes and tutorial fixes

---

CULLinary2/Assets/Scenes/MainScene.unity
CULLinary2/Assets/Scripts/Dialogue/DialogueDatabase.cs
CULLinary2/Assets/Scripts/Truck/DrivingManager.cs
CULLinary2/Assets/Scripts/UI/FollowWorldSpace.cs

Fix order pop-ups on truck camera

---

CULLinary2/Assets/Art/UI/WeaponSelect.png.meta
CULLinary2/Assets/Art/UI/recipe_select.png.meta
CULLinary2/Assets/Prefabs/UI/Creature.prefab
CULLinary2/Assets/Prefabs/UI/Panels/ChoiceUISlot.prefab
CULLinary2/Assets/Prefabs/UI/RecipeUISlot.prefab
CULLinary2/Assets/Prefabs/UI/Upgrade Slot.prefab
CULLinary2/Assets/Prefabs/UI/WeaponSlot.prefab
CULLinary2/Assets/Scenes/MainScene.unity
CULLinary2/Assets/Scripts/Dungeon/Shop/ShopManager.cs
CULLinary2/Assets/Scripts/Dungeon/Shop/ShopSlot.cs
CULLinary2/Assets/Scripts/UI/MyDialogueButton.cs
CULLinary2/Assets/Scripts/UI/MyDialogueButton.cs.meta

* Clicky sounds for dialogue
* Clicky sounds for all UI buttons
* Standardise UI sounds and selected borders

UI fixes, clicking sounds and blue corners for selection

---

CULLinary2/Assets/Scenes/MainScene.unity
CULLinary2/Assets/Scenes/TutorialScene.unity
CULLinary2/Assets/Scripts/Dialogue/DialogueManager.cs
CULLinary2/Assets/Scripts/Tutorial/TutorialUIController.cs
CULLinary2/Assets/Scripts/UI/UIController.cs

* Confirmation for skip tutorial
* Any key for dialogue in MainScene
* Fix credits stopping time
* Fix width of consumables quantity

Final fixes

---

CULLinary2/Assets/Scripts/Dialogue/DialogueDatabase.cs
CULLinary2/Assets/Scripts/Dungeon/Orders/OrdersManager.cs
CULLinary2/Assets/Scripts/UI/UIController.cs

* Use F to advance dialogue
* Update recipe UI after order generation

Final changes for dialogue F and recipe UI update
